#!/bin/sh

# Set pidgin away.
if pgrep pidgin &> /dev/null; then
    currentStatusMessage="$(purple-remote 'getstatusmessage')"
    currentStatus="$(purple-remote 'getstatus')"
    purple-remote 'setstatus?status=away&message=Away'
fi

i3lock -n -i $HOME/.wallpapers/lock.png --color=0e0e0e -u -m

if pgrep pidgin &> /dev/null; then
    purple-remote 'setstatus?status='"$currentStatus"'&message='"$currentStatusMessage"
fi
