#!/bin/sh

# Pause music
if pgrep xmms2 &> /dev/null; then
    xmms2 pause
fi

# Set pidgin away.
if pgrep pidgin &> /dev/null; then
    currentStatusMessage="$(purple-remote 'getstatusmessage')"
    currentStatus="$(purple-remote 'getstatus')"
    purple-remote 'setstatus?status=away&message=Away'
fi

#i3lock -n -i $HOME/.wallpapers/lock.png --color=0e0e0e -u -m
xscreensaver-command -lock

if pgrep pidgin &> /dev/null; then
    purple-remote 'setstatus?status='"$currentStatus"'&message='"$currentStatusMessage"
fi
